spring.application.name=lead-capture-email-automation-API

server.port=8090

spring.jpa.hibernate.ddl-auto=update

# Swagger Config
#springdoc.swagger-ui.operations-sorter=method
#springdoc.api-docs.enabled=true
#springdoc.swagger-ui.enabled=true



#spring.servlet.multipart.max-file-size=5MB


spring.sql.init.mode=always
# logging.level.org.springframework=debug
#
#spring.security.user.name=abdo
#spring.security.user.password=1234

spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MY_GMAIL}

spring.mail.password=${MY_GMAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


application.description=REST API for landing page API and lead capture email automation 
application.version=1.0

security.jwt.secret-key=dmVnZXRhYmxlYmFua2NlbnR1cnltZXJlbHlsZXR0ZXJhY3R1YWxseWV2ZXJ5dGhpbmc=

